# Generated by Django 3.2.7 on 2021-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='population',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
